networks:
  server:
    driver: bridge

services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/public/
      - ./nginx/:/etc/nginx/conf.d/
      - ./log/nginx/:/var/log/nginx/
    networks:
      - server

  php:
    container_name: php
    build: ./php/
    volumes:
      - ./app/:/var/www/public/
    networks:
      - server

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    ports:
      - 3306:3306
    networks:
      - server
    volumes:
      - db_volume:/var/lib/mysql/

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    networks:
      - server
    depends_on:
      - mysql

volumes:
  db_volume:
    driver: local
