networks:
  server:
    driver: bridge

services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/public/
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - server

  php:
    container_name: php
    build: ./php/
    volumes:
      - ./app/:/var/www/public/
    networks:
      - server
